services:
  - type: web
    name: group-meg-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
        
